### ISSUE TITLE
gitmoji 检查报错

### ISSUE THREAD

**Issue by arvinxx** [arvinxx/gitmoji-commit-workflow#12]
```
husky > commit-msg (node v10.23.0)
C:\Users\arvinxx\CodeProjects\umi-electron-template\node_modules\@commitlint\cli\lib\cli.js:100
throw err;
^

Error: Command failed: curl --silent -L https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json
at checkExecSyncError (child_process.js:629:11)
at Object.execFileSync (child_process.js:647:13)
at Object.<anonymous> (C:\Users\arvinxx\CodeProjects\umi-electron-template\node_modules\commitlint-plugin-gitmoji\lib\gitmojiCode.js:16:41)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require
```

**Comment by arvinxx** [comment]
修正后报错有更好的提示，
```
Failed to fetch gitmoji JSON, please refer to https://github.com/arvinxx/gitmoji-commit-workflow/tree/master/packages/plugin#fetch-error for help.
```
