### ISSUE TITLE
`conventional-changelog-lint-config-gitmoji` not found when running commitlint with npx

### ISSUE THREAD

**Issue by rdbisme** [arvinxx/gitmoji-commit-workflow#668]
Any idea why this: 
```
$ npx -p commitlint -p "commitlint-config-gitmoji" commitlint --from "origin/${CI_DEFAULT_BRANCH}" --to HEAD
npm WARN exec The following packages were not found and will be installed: commitlint-config-gitmoji@2.3.1, commitlint@17.6.1
Error: Cannot find module "conventional-changelog-lint-config-gitmoji" from "/builds/qupynt/qupynt-ci"
    at resolveId (/builds/qupynt/qupynt-ci/.cache/npm/_npx/49ea1ae74129e566/node_modules/@commitlint/resolve-extends/src/index.ts:131:14)
    at resolveConfig (/builds/qupynt/qupynt-ci/.cache/npm/_npx/49ea1ae74129e566/node_modules/@commitlint/resolve-extends/src/index.ts:105:20)
    at /builds/qupynt/qupynt-ci/.cache/npm/_npx/49ea1ae74129e566/node_modules/@commitlint/resolve-extends/src/index.ts:51:20
    at Array.reduce (<anonymous>)
    at loadExtends (/builds/qupynt/qupynt-ci/.cache/npm/_npx/49ea1ae74129e566/node_modules/@commitlint/resolve-extends/src/index.ts:49:13)
    at resolveExtends (/builds/qupynt/qupynt-ci/.cache/npm/_npx/49ea1ae74129e566/node_modules/@commitlint/resolve-extends/src/index.ts:25:19)
    at load (/builds/qupynt/qupynt-ci/.cache/npm/_npx/49ea1ae74129e566/node_modules/@commitlint/load/src/load.ts:56:33)
    at async main (/builds/qupynt/qupynt-ci/.cache/npm/_npx/49ea1ae74129e566/node_modules/@commitlint/cli/src/cli.ts:214:17) {
  code: 'MODULE_NOT_FOUND'
}
``` 

doesn't work? My newbieness wrt JS world might play a role here.

**Comment by arvinxx** [comment]
I will try to figure it out

**Comment by bryanjtc** [comment]
any workaround to fix this?

**Comment by joshpppp** [comment]
[](url)

**Comment by arvinxx** [comment]
@rdbisme do you try with ？

```
npx -p commitlint -p "gitmoji" commitlint --from "origin/${CI_DEFAULT_BRANCH}" --to HEAD
```

**Comment by agecode-debug** [comment]
same issue with yarn
